name: ManuMental
favicon: null
layout_spectrum: 0.23667326220311224
typography_spectrum: 0.2714215386658907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5528176072984934
  lightness: 0.25103366491384804
  saturation: 0.08485422818921506
  rhythmicContrast: 0.9889535456895828
purpose: []
